name: "GitHub Docker"
on:
  push:
    paths:
      - ".github/workflows/CI.yml"
      - "dist/index.js"
jobs:
  buildDocker:
    runs-on: ubuntu-20.04
    steps:
      - name: Publish Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ secrets.PAT }}
          containerRegistry: true